### PR TITLE
Add requirements.txt file

### PR DESCRIPTION
**Pull request by m30m**
`requirements.txt` is a standard for declaring python dependencies.
README file is updated accordingly.

### CODE REVIEW

**Comment by williamleif** [comment]
Thanks!!

**Comment by m30m** [comment]
Was there any problem that this PR isn't merged?

**Comment by RexYing** [comment]
Thanks and sorry for the delay!

**Comment by williamleif** [comment]
Apologies! I was traveling and attempted the merge from my phone on airport wifi. Thanks for pushing it through Rex.

**Comment by aksakalli** [comment]
This file has some irrelevant dependencies like `html5lib`. Actually, if you already have `conda` and tensorflow; you just need to install `networkx`...

**Comment by m30m** [comment]
`html5lib` is a dependency of `tensorboard` which is a dependency of `tensorflow`. It's a good practice to explicitly specify the versions of all required packages and not only the root packages you need. This file is usually generated using `pip freeze` command.

**Pull request merged**
